[build]
  publish = "dist"
  command = "yarn generate"

[build.environment]
  NODE_VERSION = "18.12.5"
  YARN_VERSION = "1.22.19"
  VITE_OMDB_API_KEY = "aeaa1710"

[build.cache]
  clear = true

[[plugins]]
package = "@netlify/plugin-yarn-4"
