[build]
  publish = "dist"
  command = "yarn generate"

[build.environment]
  NODE_VERSION = "20.9.0"
  YARN_VERSION = "4.0.2"
  VITE_OMDB_API_KEY = "aeaa1710"

[build.cache]
  clear = true

[[plugins]]
package = "@netlify/plugin-yarn-4"
